<?php

declare(strict_types=1);

namespace BeycanPress\CryptoPayLite;

// @phpcs:disable Generic.Files.LineLength 

use BeycanPress\CryptoPayLite\PluginHero\Hook;

class Constants
{
    /**
     * @return string
     */
    public static function getImagesUrl(): string
    {
        return Helpers::getProp('pluginUrl') . 'assets/images/';
    }

    /**
     * @return string
     */
    public static function getApiUrl(): string
    {
        return Helpers::getAPI('RestAPI')->getUrl();
    }

    /**
     * @return object<string>'
     */
    public static function getLangParams(): object
    {
        return (object) Hook::callFilter('lang', [
            "selectNetwork" => esc_html__('Select network', 'cryptopay_lite'),
            "orderId" => esc_html__('Order ID:', 'cryptopay_lite'),
            "orderAmount" => esc_html__('Order amount:', 'cryptopay_lite'),
            "selectedNetwork" => esc_html__('Selected network:', 'cryptopay_lite'),
            "waitingBlockConfirmations" => esc_html__('Waiting for block confirmations:', 'cryptopay_lite'),
            "waitingTransactionConfirmations" => esc_html__('Waiting for transaction confirmation...', 'cryptopay_lite'),
            "openInExplorer" => esc_html__('Open in explorer', 'cryptopay_lite'),
            "waitingConfirmation" => esc_html__('Waiting confirmation...', 'cryptopay_lite'),
            "selectWallet" => esc_html__('Select wallet', 'cryptopay_lite'),
            "selectPaymentMethod" => esc_html__('Select payment method', 'cryptopay_lite'),
            "pleaseTryToConnectAgain" => esc_html__('Please try to connect again by selecting network {networkName} from your wallet!', 'cryptopay_lite'),
            "walletConnectionTimedOut" => esc_html__('Wallet connection timed out!', 'cryptopay_lite'),
            "connectionError" => esc_html__('Connection error!', 'cryptopay_lite'),
            "paymentCurrency" => esc_html__('Payment currency:', 'cryptopay_lite'),
            "amountToBePaid" => esc_html__('Amount to be paid:', 'cryptopay_lite'),
            "payNow" => esc_html__('Pay now', 'cryptopay_lite'),
            "payWith" => esc_html__('Pay with {name}', 'cryptopay_lite'),
            "loading" => esc_html__('Loading...', 'cryptopay_lite'),
            "waitingApproval" => esc_html__('Waiting approval...', 'cryptopay_lite'),
            "paymentRejected" => esc_html__('Payment rejected!', 'cryptopay_lite'),
            "transferAmountError" => esc_html__('Transfer amount need to be bigger from zero!', 'cryptopay_lite'),
            "transactionCreateFail" => esc_html__('Transaction create fail! Please try again.', 'cryptopay_lite'),
            "pleaseTryAgain" => esc_html__('Please try again!', 'cryptopay_lite'),
            "insufficientBalance" => esc_html__('Insufficient balance!', 'cryptopay_lite'),
            "openWallet" => esc_html__('Open wallet', 'cryptopay_lite'),
            "paymentAddress" => esc_html__('Payment address:', 'cryptopay_lite'),
            "paymentTimedOut" => esc_html__('Payment timed out!', 'cryptopay_lite'),
            "connectionRejected" => esc_html__('Connection rejected!', 'cryptopay_lite'),
            "pleaseWait" => esc_html__('Please wait...', 'cryptopay_lite'),
            "convertingError" => esc_html__('There was a problem converting currency! Make sure your currency value is available in the relevant API or you define a custom price value for your currency.', 'cryptopay_lite'),
            "transactionSent" => esc_html__('Transaction sent', 'cryptopay_lite'),
            "notFoundAnyWallet" => esc_html__('No working wallet was found on this network. Please make sure you have a {networkName} wallet working on the browser or contact the administrator regarding the situation.', 'cryptopay_lite'),
            "alreadyProcessing" => esc_html__('There is currently a process on the wallet. Please try again after completing the relevant process.', 'cryptopay_lite'),
            "wallet-not-found" => esc_html__('Wallet not found!', 'cryptopay_lite'),
            "rpcAccessForbidden" => esc_html__('RPC Address refused to connect (This is not an error!). Blockchain networks main RCP API addresses are public, so it can restrict you, in which case you need to get a unique RPC API address from any provider as stated in the documentation. Please report the situation to the site administrator.', 'cryptopay_lite'),
            "rpcConnectionError" => esc_html__('This is an RPC connection error. The relevant RPC address may have been entered incorrectly, or if it is a public RPC, your IP address may have been banned. So please make sure everything is OK. Try custom RPC providers. Please report the situation to the site administrator.', 'cryptopay_lite'),
            "invalidAddress" => esc_html__('Failed to match network with corresponding payout wallet. Please notify the site administrator of the situation.', 'cryptopay_lite'),
            "anyError" => esc_html__('An unexpected error has occurred, please try again or contact the site administrator.', 'cryptopay_lite'),
            "continuePaymentProcess" => esc_html__('Continue payment process', 'cryptopay_lite'),
            'defaultErrorMsg' => esc_html__('Error processing checkout. Please try again.', 'cryptopay_lite'),
            "checkingForm" => esc_html__('Checking form data! Please wait...', 'cryptopay_lite'),
            "tokenMetadataNotFound" => esc_html__('Token metadata not found!', 'cryptopay_lite'),
            "moralisApiKeyNotSet" => esc_html__('Moralis API key not set! Please contact the site administrator.', 'cryptopay_lite'),
            "detected" => esc_html__('Detected', 'cryptopay_lite'),
            "download" => esc_html__('Download', 'cryptopay_lite'),
            "openInApp" => esc_html__('Open In App', 'cryptopay_lite'),
            "openInAppManual" => esc_html__('Open In App (Manual)', 'cryptopay_lite'),
            "onlyDesktop" => esc_html__('Only Desktop', 'cryptopay_lite'),
            "websocketConnectionFailed" => esc_html__('Websocket connection failed!', 'cryptopay_lite'),
            "websocketNotSupported" => esc_html__('A transaction was caught, but execution aborted due to an error on Websocket. Please specify a supported Websocket address.', 'cryptopay_lite'),
            "change" => esc_html__('Change', 'cryptopay_lite'),
            "changeNetwork" => esc_html__('Change network', 'cryptopay_lite'),
            "web3Domain" => esc_html__('Web3 Domain: ', 'cryptopay_lite'),
            "notFoundAnyCurrency" => esc_html__('No active currencies were found on this network. Please report this to the administrator.', 'cryptopay_lite'),
            "notFoundAnyCurrencyForPayment" => esc_html__('Sorry, no currency found! Please report this to the administrator.', 'cryptopay_lite'),
            "notFoundAnyNetworkForPayment" => esc_html__('Sorry, no network found! Please report this to the administrator.', 'cryptopay_lite'),
            "paymentCompleting" => esc_html__('Payment is being completed, please wait...', 'cryptopay_lite'),
            "openInAppMsg" => esc_html__('This is a informational message. You tried to redirect to the application with Deep Link. If no application guidance has been made. It means you do not have the relevant wallet application. Please get the relevant wallet app from the app market.', 'cryptopay_lite'),
            "openInAppManualMsg" => esc_html__('This is an informational message. This wallet does not support Deep Linking. Therefore, you can try to connect to this wallet directly using the browser in the application.', 'cryptopay_lite'),
            "onlyDesktopMsg" => esc_html__('This is an informational message. This wallet does not have support on mobile platforms. So please try connecting to the wallet via a desktop browser.', 'cryptopay_lite'),
            "downloadManualMsg" => esc_html__('This is an informational message. No download link is provided for this wallet. So please try connecting after downloading the wallet.', 'cryptopay_lite'),
            "downloadMsg" => esc_html__('This is an informational message. You were redirected to the download link because the relevant wallet could not be detected in your browser. Please try connecting again after installing the wallet.', 'cryptopay_lite'),
            "processing" => esc_html__('Processing...', 'cryptopay_lite'),
            "instantPaymentMsg" => esc_html__('This is an informational message. Instant payment data not loaded. Please report the situation to the site administrator', 'cryptopay_lite'),
            "email" => esc_html__('Email', 'cryptopay_lite'),
            "save" => esc_html__('Save', 'cryptopay_lite'),
            "enterYourEmailAddress" => esc_html__('Enter your email address', 'cryptopay_lite'),
            "pleaseEnterAValidEmailAddress" => esc_html__('Please enter a valid email address', 'cryptopay_lite'),
            "importantInformation" => esc_html__('Important information', 'cryptopay_lite'),
            "continue" => esc_html__('Continue', 'cryptopay_lite'),
            "selectCurrency" => esc_html__('Select currency', 'cryptopay_lite'),
            "gettingPrice" => esc_html__('The price is being taken...', 'cryptopay_lite'),
            "search" => esc_html__('Search', 'cryptopay_lite'),
            "connectionWallet" => esc_html__('Connecting to wallet...', 'cryptopay_lite'),
            "discount" => esc_html__('Discount', 'cryptopay_lite'),
            "checkingSanctions" => esc_html__('Checking address sanctions...', 'cryptopay_lite'),
            "sanctionedMessage" => esc_html__('Your wallet has been marked by some sanction-controlling platforms. That \'s why we don\'t accept payments from this wallet address. {source}', 'cryptopay_lite'),
            "source" => esc_html__('Source:', 'cryptopay_lite'),
            "rpcTimeout" => esc_html__('RPC Timeout! We cannot continue the process because the RPC API of the current blockchain does not respond to our requests. Please report this to the website administrator!', 'cryptopay_lite'),
            "redirecting" => esc_html__('Redirecting...', 'cryptopay_lite'),
            "connecting" => esc_html__('Connecting...', 'cryptopay_lite'),
        ]);
    }

    /**
     * @return array<string,string>
     */
    public static function getCountryCurrencies(): array
    {
        return [
            'USD' => 'United States Dollar',
            'EUR' => 'Euro Member Countries',
            'GBP' => 'United Kingdom Pound',
            'ALL' => 'Albania Lek',
            'AFN' => 'Afghanistan Afghani',
            'ARS' => 'Argentina Peso',
            'AWG' => 'Aruba Guilder',
            'AUD' => 'Australia Dollar',
            'AZN' => 'Azerbaijan New Manat',
            'BSD' => 'Bahamas Dollar',
            'BBD' => 'Barbados Dollar',
            'BDT' => 'Bangladeshi taka',
            'BYR' => 'Belarus Ruble',
            'BZD' => 'Belize Dollar',
            'BMD' => 'Bermuda Dollar',
            'BOB' => 'Bolivia Boliviano',
            'BAM' => 'Bosnia and Herzegovina Convertible Marka',
            'BWP' => 'Botswana Pula',
            'BGN' => 'Bulgaria Lev',
            'BRL' => 'Brazil Real',
            'BND' => 'Brunei Darussalam Dollar',
            'KHR' => 'Cambodia Riel',
            'CAD' => 'Canada Dollar',
            'KYD' => 'Cayman Islands Dollar',
            'CLP' => 'Chile Peso',
            'CNY' => 'China Yuan Renminbi',
            'COP' => 'Colombia Peso',
            'CRC' => 'Costa Rica Colon',
            'HRK' => 'Croatia Kuna',
            'CUP' => 'Cuba Peso',
            'CZK' => 'Czech Republic Koruna',
            'DKK' => 'Denmark Krone',
            'DOP' => 'Dominican Republic Peso',
            'XCD' => 'East Caribbean Dollar',
            'EGP' => 'Egypt Pound',
            'SVC' => 'El Salvador Colon',
            'EEK' => 'Estonia Kroon',
            'FKP' => 'Falkland Islands (Malvinas) Pound',
            'FJD' => 'Fiji Dollar',
            'GHC' => 'Ghana Cedis',
            'GIP' => 'Gibraltar Pound',
            'GTQ' => 'Guatemala Quetzal',
            'GGP' => 'Guernsey Pound',
            'GYD' => 'Guyana Dollar',
            'HNL' => 'Honduras Lempira',
            'HKD' => 'Hong Kong Dollar',
            'HUF' => 'Hungary Forint',
            'ISK' => 'Iceland Krona',
            'INR' => 'India Rupee',
            'IDR' => 'Indonesia Rupiah',
            'IRR' => 'Iran Rial',
            'IMP' => 'Isle of Man Pound',
            'ILS' => 'Israel Shekel',
            'JMD' => 'Jamaica Dollar',
            'JPY' => 'Japan Yen',
            'JEP' => 'Jersey Pound',
            'KZT' => 'Kazakhstan Tenge',
            'KPW' => 'Korea (North) Won',
            'KRW' => 'Korea (South) Won',
            'KGS' => 'Kyrgyzstan Som',
            'LAK' => 'Laos Kip',
            'LVL' => 'Latvia Lat',
            'LBP' => 'Lebanon Pound',
            'LRD' => 'Liberia Dollar',
            'LTL' => 'Lithuania Litas',
            'MKD' => 'Macedonia Denar',
            'MYR' => 'Malaysia Ringgit',
            'MUR' => 'Mauritius Rupee',
            'MXN' => 'Mexico Peso',
            'MNT' => 'Mongolia Tughrik',
            'MZN' => 'Mozambique Metical',
            'NAD' => 'Namibia Dollar',
            'NPR' => 'Nepal Rupee',
            'ANG' => 'Netherlands Antilles Guilder',
            'NZD' => 'New Zealand Dollar',
            'NIO' => 'Nicaragua Cordoba',
            'NGN' => 'Nigeria Naira',
            'NOK' => 'Norway Krone',
            'OMR' => 'Oman Rial',
            'PKR' => 'Pakistan Rupee',
            'PAB' => 'Panama Balboa',
            'PYG' => 'Paraguay Guarani',
            'PEN' => 'Peru Nuevo Sol',
            'PHP' => 'Philippines Peso',
            'PLN' => 'Poland Zloty',
            'QAR' => 'Qatar Riyal',
            'RON' => 'Romania New Leu',
            'RUB' => 'Russia Ruble',
            'SHP' => 'Saint Helena Pound',
            'SAR' => 'Saudi Arabia Riyal',
            'RSD' => 'Serbia Dinar',
            'SCR' => 'Seychelles Rupee',
            'SGD' => 'Singapore Dollar',
            'SBD' => 'Solomon Islands Dollar',
            'SOS' => 'Somalia Shilling',
            'ZAR' => 'South Africa Rand',
            'LKR' => 'Sri Lanka Rupee',
            'SEK' => 'Sweden Krona',
            'CHF' => 'Switzerland Franc',
            'SRD' => 'Suriname Dollar',
            'SYP' => 'Syria Pound',
            'TWD' => 'Taiwan New Dollar',
            'THB' => 'Thailand Baht',
            'TTD' => 'Trinidad and Tobago Dollar',
            'TRY' => 'Turkey Lira',
            'TRL' => 'Turkey Lira',
            'TVD' => 'Tuvalu Dollar',
            'UAH' => 'Ukraine Hryvna',
            'UYU' => 'Uruguay Peso',
            'UZS' => 'Uzbekistan Som',
            'VEF' => 'Venezuela Bolivar',
            'VND' => 'Viet Nam Dong',
            'YER' => 'Yemen Rial',
            'ZWD' => 'Zimbabwe Dollar'
        ];
    }
}
