name: Create auto release

on: 
  push:
    branches:
      - master

jobs:
  auto_release:
    name: Auto release
    permissions: write-all
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout repository
      uses: actions/checkout@master

    - name: Extract version from commit message
      id: extract_version
      run: |
        VERSION=$(git log --format=%B -n 1 ${{ github.sha }} | grep -o -E '[0-9]+\.[0-9]+\.[0-9]+' || true)
        if [ -z "$VERSION" ]; then
          exit 1
        fi
        echo "::set-output name=version::$VERSION"

    - name: Create Release
      id: create_release
      if: steps.extract_version.outputs.version
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.extract_version.outputs.version }}
        release_name: Version ${{ steps.extract_version.outputs.version }}
        body: Version ${{ steps.extract_version.outputs.version }}
        draft: false
        prerelease: false