name: Publish to WordPress.org

on:
  release:
    types:
      - published
    branches:
      - master

env:
  PLUGIN_SLUG: cryptopay-wc-lite

jobs:
  deploy_to_wp_org:
    permissions: write-all
    name: WordPress.org Plugin Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@master

    - name: WordPress Plugin Deploy
      id: deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      with:
        generate-zip: true
      env:
        SVN_PASSWORD: ${{ secrets.WORDPRESS_ORG_PASSWORD }}
        SVN_USERNAME: ${{ secrets.WORDPRESS_ORG_USERNAME }}
        SLUG: ${{ env.PLUGIN_SLUG }}
    
    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ steps.deploy.outputs.zip-path }}
        asset_name: ${{ env.PLUGIN_SLUG }}.zip
        asset_content_type: application/zip
